angular.module('enhancedWars.defaultMaps', []).
  factory('DefaultMaps', [->
    [
      {"name":"Bombed out","description":"","data":[[{"terrainVariant":5,"building":"dropzone","terrain":"road","x":0,"unit":"none","y":0,"buildingFaction":1,"buildingVariant":1},{"terrainVariant":1,"building":"none","unitFaction":0,"terrain":"road","x":0,"unit":"mediumTank","y":1,"unitOrientation":"down"},{"terrainVariant":1,"building":"none","terrain":"road","x":0,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"plain","x":0,"unit":"none","y":3},{"terrainVariant":4,"building":"none","terrain":"road","x":0,"unit":"none","y":4},{"terrainVariant":2,"building":"none","terrain":"forrest","x":0,"unit":"none","y":5},{"terrainVariant":2,"building":"none","terrain":"dessert","x":0,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"mountain","x":0,"unit":"none","y":7},{"terrainVariant":0,"building":"dropzone","terrain":"plain","x":0,"unit":"none","y":8,"buildingFaction":"neutral","buildingVariant":0}],[{"terrainVariant":0,"building":"none","terrain":"road","x":1,"unit":"none","y":0},{"terrainVariant":1,"building":"none","terrain":"forrest","x":1,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":1,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":1,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":1,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"forrest","x":1,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"forrest","x":1,"unit":"none","y":6},{"terrainVariant":1,"building":"none","terrain":"dessert","x":1,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":1,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"plain","x":2,"unit":"none","y":0},{"terrainVariant":1,"building":"none","terrain":"dessert","x":2,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":2,"unit":"none","y":2},{"terrainVariant":2,"building":"none","terrain":"forrest","x":2,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":2,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"forrest","x":2,"unit":"none","y":5},{"terrainVariant":1,"building":"none","terrain":"dessert","x":2,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":2,"unit":"none","y":7},{"terrainVariant":2,"building":"none","terrain":"dessert","x":2,"unit":"none","y":8}],[{"terrainVariant":1,"building":"none","terrain":"plain","x":3,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":3,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"forrest","x":3,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"forrest","x":3,"unit":"none","y":3},{"terrainVariant":1,"building":"none","terrain":"dessert","x":3,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":3,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":3,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"mountain","x":3,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"dessert","x":3,"unit":"none","y":8}],[{"terrainVariant":2,"building":"none","terrain":"road","x":4,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"road","x":4,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":3},{"terrainVariant":6,"building":"none","terrain":"road","x":4,"unit":"none","y":4},{"terrainVariant":2,"building":"none","terrain":"forrest","x":4,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":8}],[{"terrainVariant":2,"building":"none","terrain":"dessert","x":5,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"mountain","x":5,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":5,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":5,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":5,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"forrest","x":5,"unit":"none","y":5},{"terrainVariant":2,"building":"none","terrain":"mountain","x":5,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":5,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"dessert","x":5,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":6,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":6,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"mountain","x":6,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"forrest","x":6,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":4},{"terrainVariant":2,"building":"none","terrain":"forrest","x":6,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"forrest","x":6,"unit":"none","y":6},{"terrainVariant":1,"building":"none","terrain":"dessert","x":6,"unit":"none","y":7},{"terrainVariant":1,"building":"none","terrain":"mountain","x":6,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"mountain","x":7,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":7,"unit":"none","y":1,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":0,"building":"none","terrain":"forrest","x":7,"unit":"none","y":2},{"terrainVariant":2,"building":"none","terrain":"forrest","x":7,"unit":"none","y":3},{"terrainVariant":0,"building":"dropzone","terrain":"road","x":7,"unit":"none","y":4,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":1,"building":"none","terrain":"forrest","x":7,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":7,"unit":"none","y":6},{"terrainVariant":2,"building":"none","terrain":"dessert","x":7,"unit":"none","y":7,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":7,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":8,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"forrest","x":8,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"mountain","x":8,"unit":"none","y":6},{"terrainVariant":5,"building":"none","terrain":"road","x":8,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"dessert","x":9,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"forrest","x":9,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":9,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"mountain","x":9,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":10,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"mountain","x":10,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":10,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":10,"unit":"none","y":3},{"terrainVariant":6,"building":"none","terrain":"road","x":10,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"road","x":10,"unit":"none","y":5},{"terrainVariant":3,"building":"none","terrain":"road","x":10,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":10,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"dessert","x":10,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"mountain","x":11,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":11,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"dessert","x":11,"unit":"none","y":2},{"terrainVariant":2,"building":"none","terrain":"forrest","x":11,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":11,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"forrest","x":11,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":11,"unit":"none","y":6},{"terrainVariant":1,"building":"none","terrain":"dessert","x":11,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":11,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":0},{"terrainVariant":2,"building":"none","terrain":"dessert","x":12,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"forrest","x":12,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":12,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"forrest","x":12,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":7},{"terrainVariant":1,"building":"none","terrain":"plain","x":12,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"plain","x":13,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":13,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":13,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"dessert","x":13,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":13,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"forrest","x":13,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"forrest","x":13,"unit":"none","y":6},{"terrainVariant":2,"building":"none","unitFaction":1,"terrain":"forrest","x":13,"unit":"lightTank","y":7,"unitOrientation":"right"},{"terrainVariant":0,"building":"none","terrain":"road","x":13,"unit":"none","y":8}],[{"terrainVariant":0,"building":"dropzone","terrain":"plain","x":14,"unit":"none","y":0,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":1,"building":"none","terrain":"mountain","x":14,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"dessert","x":14,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":14,"unit":"none","y":3},{"terrainVariant":2,"building":"none","terrain":"road","x":14,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"road","x":14,"unit":"none","y":5},{"terrainVariant":1,"building":"none","terrain":"plain","x":14,"unit":"none","y":6},{"terrainVariant":1,"building":"none","unitFaction":1,"terrain":"road","x":14,"unit":"mediumTank","y":7,"unitOrientation":"up"},{"terrainVariant":3,"building":"dropzone","terrain":"road","x":14,"unit":"none","y":8,"buildingFaction":2,"buildingVariant":2}]]},
      {"name":"Tri-lands","description":"","data":[[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"forrest","x":0,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":0,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":7},{"terrainVariant":0,"building":"dropzone","terrain":"plain","x":0,"unit":"none","y":8,"buildingFaction":1,"buildingVariant":1}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"dessert","x":1,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":1,"unit":"none","y":5},{"terrainVariant":1,"building":"none","terrain":"plain","x":1,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":1,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":1,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":2,"unit":"none","y":0},{"terrainVariant":5,"building":"none","terrain":"road","x":2,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"road","x":2,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"road","x":2,"unit":"none","y":3},{"terrainVariant":1,"building":"none","terrain":"road","x":2,"unit":"none","y":4},{"terrainVariant":0,"building":"none","unitFaction":0,"terrain":"dessert","x":2,"unit":"lightTank","y":5,"unitOrientation":"up"},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":2,"unit":"none","y":6},{"terrainVariant":0,"building":"none","unitFaction":0,"terrain":"plain","x":2,"unit":"lightTank","y":7,"unitOrientation":"right"},{"terrainVariant":0,"building":"none","terrain":"forrest","x":2,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":3,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":3,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":3,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":3,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"mountain","x":3,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"plain","x":3,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":3,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":3,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":3,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":4,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":4,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":4,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":4,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":5},{"terrainVariant":1,"building":"none","terrain":"plain","x":4,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"mountain","x":4,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":5,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":5,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":5,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":7,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"plain","x":7,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":7,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":7,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"forrest","x":8,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"forrest","x":8,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"plain","x":8,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":8,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":8,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":8,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":8,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":8,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"plain","x":9,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"plain","x":9,"unit":"none","y":1},{"terrainVariant":0,"building":"dropzone","terrain":"plain","x":9,"unit":"none","y":2,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":0,"building":"none","terrain":"mountain","x":9,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":9,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":9,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":9,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":9,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":9,"unit":"none","y":8}],[{"terrainVariant":1,"building":"none","terrain":"plain","x":10,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"forrest","x":10,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":10,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"plain","x":10,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":10,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":10,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":10,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":10,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":10,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":11,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":11,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":11,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":11,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":11,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":11,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":11,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":11,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":11,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":12,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":12,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":12,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":13,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":13,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":13,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":13,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":14,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":14,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":14,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":14,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"mountain","x":14,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":14,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":14,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":14,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":14,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":15,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":15,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":15,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":15,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"mountain","x":15,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":15,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":15,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"plain","x":15,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"mountain","x":15,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":16,"unit":"none","y":0},{"terrainVariant":2,"building":"none","terrain":"road","x":16,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"road","x":16,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"road","x":16,"unit":"none","y":3},{"terrainVariant":1,"building":"none","terrain":"road","x":16,"unit":"none","y":4},{"terrainVariant":0,"building":"none","unitFaction":1,"terrain":"dessert","x":16,"unit":"lightTank","y":5,"unitOrientation":"up"},{"terrainVariant":0,"building":"none","unitFaction":1,"terrain":"plain","x":16,"unit":"mediumTank","y":6,"unitOrientation":"left"},{"terrainVariant":0,"building":"none","unitFaction":1,"terrain":"dessert","x":16,"unit":"lightTank","y":7,"unitOrientation":"left"},{"terrainVariant":0,"building":"none","terrain":"forrest","x":16,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":17,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":17,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":17,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":17,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":17,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"plain","x":17,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":17,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":17,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":17,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":18,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":18,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"plain","x":18,"unit":"none","y":7},{"terrainVariant":0,"building":"dropzone","terrain":"plain","x":18,"unit":"none","y":8,"buildingFaction":2,"buildingVariant":2}]]},
      {"name":"Tiny Delta","description":"","data":[[{"terrainVariant":0,"building":"none","terrain":"dessert","x":0,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"plain","x":0,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"plain","x":0,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"road","x":0,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"plain","x":0,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"mountain","x":0,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":0,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":0,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":0,"unit":"none","y":8}],[{"terrainVariant":5,"building":"none","terrain":"road","x":1,"unit":"none","y":0},{"terrainVariant":1,"building":"dropzone","terrain":"road","x":1,"unit":"none","y":1,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":1,"building":"none","terrain":"road","x":1,"unit":"none","y":2},{"terrainVariant":6,"building":"none","terrain":"road","x":1,"unit":"none","y":3},{"terrainVariant":4,"building":"none","terrain":"road","x":1,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":1,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"mountain","x":1,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"road","x":2,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"dessert","x":2,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"plain","x":2,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"forrest","x":2,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":2,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"mountain","x":2,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":2,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"dessert","x":2,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":2,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"road","x":3,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"forrest","x":3,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":3,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":3,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":3,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"plain","x":3,"unit":"none","y":5},{"terrainVariant":1,"building":"none","terrain":"plain","x":3,"unit":"none","y":6},{"terrainVariant":5,"building":"none","terrain":"road","x":3,"unit":"none","y":7},{"terrainVariant":1,"building":"none","terrain":"road","x":3,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":4,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"dessert","x":4,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"plain","x":4,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":4,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":4,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":4,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":4,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"road","x":5,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"plain","x":5,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":5,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":5,"unit":"none","y":3},{"terrainVariant":2,"building":"none","terrain":"road","x":5,"unit":"none","y":4},{"terrainVariant":1,"building":"dropzone","unitFaction":0,"terrain":"road","x":5,"unit":"lightTank","y":5,"buildingFaction":1,"unitOrientation":"right","buildingVariant":1},{"terrainVariant":1,"building":"none","terrain":"road","x":5,"unit":"none","y":6},{"terrainVariant":6,"building":"none","terrain":"road","x":5,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":5,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"forrest","x":6,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"mountain","x":6,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"plain","x":6,"unit":"none","y":4},{"terrainVariant":1,"building":"none","terrain":"plain","x":6,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":6,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":6,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":6,"unit":"none","y":8}],[{"terrainVariant":2,"building":"none","terrain":"road","x":7,"unit":"none","y":0},{"terrainVariant":4,"building":"dropzone","unitFaction":1,"terrain":"road","x":7,"unit":"lightTank","y":1,"buildingFaction":2,"unitOrientation":"down","buildingVariant":2},{"terrainVariant":0,"building":"none","unitFaction":1,"terrain":"dessert","x":7,"unit":"mediumTank","y":2,"unitOrientation":"down"},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":7,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"plain","x":7,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"plain","x":7,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"plain","x":7,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":7,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"pineForrest","x":7,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"mountain","x":8,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":8,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"plain","x":8,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":8,"unit":"none","y":3},{"terrainVariant":1,"building":"none","terrain":"plain","x":8,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"dessert","x":8,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":8,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"road","x":8,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":8,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"mountain","x":9,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":9,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"plain","x":9,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":9,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"dessert","x":9,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":9,"unit":"none","y":5},{"terrainVariant":5,"building":"none","terrain":"road","x":9,"unit":"none","y":6},{"terrainVariant":3,"building":"none","terrain":"road","x":9,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":9,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"plain","x":10,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":10,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"plain","x":10,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"dessert","x":10,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":10,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"forrest","x":10,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"road","x":10,"unit":"none","y":6},{"terrainVariant":0,"building":"none","terrain":"plain","x":10,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"plain","x":10,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"plain","x":11,"unit":"none","y":0},{"terrainVariant":6,"building":"none","terrain":"road","x":11,"unit":"none","y":1},{"terrainVariant":1,"building":"none","terrain":"road","x":11,"unit":"none","y":2},{"terrainVariant":1,"building":"none","terrain":"road","x":11,"unit":"none","y":3},{"terrainVariant":1,"building":"none","terrain":"road","x":11,"unit":"none","y":4},{"terrainVariant":6,"building":"none","terrain":"road","x":11,"unit":"none","y":5},{"terrainVariant":6,"building":"none","terrain":"road","x":11,"unit":"none","y":6},{"terrainVariant":1,"building":"dropzone","terrain":"road","x":11,"unit":"none","y":7,"buildingFaction":"neutral","buildingVariant":0},{"terrainVariant":1,"building":"none","terrain":"road","x":11,"unit":"none","y":8}],[{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":0},{"terrainVariant":0,"building":"none","terrain":"road","x":12,"unit":"none","y":1},{"terrainVariant":0,"building":"none","terrain":"forrest","x":12,"unit":"none","y":2},{"terrainVariant":0,"building":"none","terrain":"deepWater","x":12,"unit":"none","y":3},{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":4},{"terrainVariant":0,"building":"none","terrain":"road","x":12,"unit":"none","y":5},{"terrainVariant":0,"building":"none","terrain":"dessert","x":12,"unit":"none","y":6},{"terrainVariant":1,"building":"none","terrain":"plain","x":12,"unit":"none","y":7},{"terrainVariant":0,"building":"none","terrain":"mountain","x":12,"unit":"none","y":8}]]},
      ({
        data: [
          [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 0
            }, {
              building: "none",
              buildingFaction: "neutral",
              buildingVariant: 0,
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 2
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 3
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 4
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 2,
              unit: "none",
              x: 0,
              y: 5
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 6
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 0,
              y: 7
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 8
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 0,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 0
            }, {
              building: "dropzone",
              buildingFaction: 1,
              buildingVariant: 1,
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 2
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 4
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 5
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 2,
              unit: "none",
              x: 1,
              y: 6
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 2,
              unit: "none",
              x: 1,
              y: 7
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 8
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 9
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 1,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "road",
              terrainVariant: 1,
              unit: "mediumTank",
              unitFaction: 0,
              unitOrientation: "down",
              x: 2,
              y: 0
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 1,
              unit: "none",
              x: 2,
              y: 1
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 1,
              unit: "none",
              unitFaction: 1,
              unitOrientation: "right",
              x: 2,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 4,
              unit: "none",
              x: 2,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 2,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 2,
              y: 5
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 2,
              y: 6
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 1,
              unit: "none",
              x: 2,
              y: 7
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 1,
              unit: "none",
              x: 2,
              y: 8
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 2,
              y: 9
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 2,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 2,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 2,
              unit: "none",
              x: 3,
              y: 0
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 2,
              unit: "none",
              x: 3,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 3,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 5
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 6
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 1,
              unit: "none",
              x: 3,
              y: 7
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 8
            }, {
              building: "dropzone",
              buildingFaction: "neutral",
              buildingVariant: 0,
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 9
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 3,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 2,
              unit: "none",
              x: 4,
              y: 0
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 1
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 3
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 1,
              unit: "none",
              x: 4,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 5
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 4,
              y: 6
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 7
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 8
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 4,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 0
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 1,
              unit: "none",
              x: 5,
              y: 1
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 3
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 5
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 6
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 7
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 8
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 9
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 5,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 0
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 6,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 6,
              y: 5
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 6
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 7
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 8
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 6,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 0
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 3
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 4
            }, {
              building: "dropzone",
              buildingFaction: "neutral",
              buildingVariant: 0,
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 5
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 6
            }, {
              building: "none",
              terrain: "dessert",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 7
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 8
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 7,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 0
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 1
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 3
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 4
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 5
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 6
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 7
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 8
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 8,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 0
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 4
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 5
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 6
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 7
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 8
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 9
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 10
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 9,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 0
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 1
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 10,
              y: 4
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 1,
              unit: "none",
              x: 10,
              y: 5
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 1,
              unit: "none",
              x: 10,
              y: 6
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "mediumArtillery",
              x: 10,
              y: 7,
              unitFaction: 1,
              unitOrientation: "left"
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 1,
              unit: "none",
              x: 10,
              y: 8
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 9
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 10
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 10,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 0
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 1
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 1,
              unit: "none",
              x: 11,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 5
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 6
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 7
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 2,
              unit: "none",
              x: 11,
              y: 8
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 9
            }, {
              building: "none",
              terrain: "shallowWater",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 10
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 11,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 0
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 1
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 3
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 5
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 6
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 1,
              unit: "none",
              x: 12,
              y: 7
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 8
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 9
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 10
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 12,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 0
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "heavyTank",
              x: 13,
              y: 3,
              unitFaction: 1,
              unitOrientation: "left"
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 4
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 5
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 1,
              unit: "none",
              x: 13,
              y: 6
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 7
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 8
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 9
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 10
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 13,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "forrest",
              terrainVariant: 1,
              unit: "none",
              x: 14,
              y: 0
            }, {
              building: "none",
              terrain: "forrest",
              terrainVariant: 2,
              unit: "none",
              x: 14,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 2
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 2,
              unit: "none",
              x: 14,
              y: 3
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 1,
              unit: "none",
              x: 14,
              y: 4
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 4,
              unit: "mediumTank",
              unitFaction: 1,
              unitOrientation: "up",
              x: 14,
              y: 5
            }, {
              building: "dropzone",
              buildingFaction: 2,
              buildingVariant: 2,
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 6
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 7
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 8
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 9
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 1,
              unit: "none",
              x: 14,
              y: 10
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 14,
              y: 11
            }
          ], [
            {
              building: "none",
              terrain: "forrest",
              terrainVariant: 2,
              unit: "none",
              x: 15,
              y: 0
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 1
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 2
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 3
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 4
            }, {
              building: "none",
              terrain: "road",
              terrainVariant: 0,
              unit: "none",
              unitFaction: 0,
              unitOrientation: "right",
              x: 15,
              y: 5
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 2,
              unit: "none",
              x: 15,
              y: 6
            }, {
              building: "none",
              terrain: "plain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 7
            }, {
              building: "none",
              terrain: "pineForrest",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 8
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 9
            }, {
              building: "none",
              terrain: "mountain",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 10
            }, {
              building: "none",
              terrain: "deepWater",
              terrainVariant: 0,
              unit: "none",
              x: 15,
              y: 11
            }
          ]
        ],
        description: "",
        name: "River Land"
      }),

      ({
        name: "Aruba by Casaubon",
        description: "",
        data: [
          [
            {
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 6
            }, {
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 7
            }, {
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 8
            }, {
              building: "none",
              terrain: "none",
              x: 0,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 1,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 2,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 1,
              unit: "none",
              y: 6
            }, {
              building: "none",
              terrain: "none",
              x: 1,
              unit: "none",
              y: 7
            }, {
              building: "none",
              terrain: "none",
              x: 1,
              unit: "none",
              y: 8
            }, {
              building: "none",
              terrain: "none",
              x: 1,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 2,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 2,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "pineForrest",
              x: 2,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 1,
              building: "dropzone",
              terrain: "pineForrest",
              x: 2,
              unit: "none",
              y: 3,
              buildingFaction: 1,
              buildingVariant: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 2,
              unit: "none",
              y: 4,
              buildingFaction: "neutral",
              buildingVariant: 0
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 2,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 2,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 2,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 2,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 2,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 3,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 3,
              building: "none",
              terrain: "mountain",
              x: 3,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "pineForrest",
              x: 3,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 1,
              building: "none",
              unitFaction: 0,
              terrain: "plain",
              x: 3,
              unit: "none",
              y: 3,
              buildingFaction: "neutral",
              unitOrientation: "right",
              buildingVariant: 0
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 3,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 3,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 3,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "forrest",
              x: 3,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 3,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 3,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "none",
              x: 4,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 4,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "dropzone",
              terrain: "plain",
              x: 4,
              unit: "none",
              y: 2,
              buildingFaction: "neutral",
              buildingVariant: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 4,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 4,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 4,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "forrest",
              x: 4,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "forrest",
              x: 4,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 4,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 4,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 5,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 5,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 5,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 5,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 2,
              building: "none",
              terrain: "pineForrest",
              x: 5,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 5,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 2,
              building: "none",
              terrain: "forrest",
              x: 5,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 5,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 5,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 2,
              building: "none",
              terrain: "mountain",
              x: 5,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 6,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 6,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "dessert",
              x: 6,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "pineForrest",
              x: 6,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "pineForrest",
              x: 6,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 6,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 6,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 6,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 6,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 6,
              unit: "none",
              y: 9
            }
          ], [
            {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 7,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "shallowWater",
              x: 7,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "dessert",
              x: 7,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 2,
              building: "none",
              terrain: "pineForrest",
              x: 7,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "pineForrest",
              x: 7,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 7,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 7,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 1,
              building: "none",
              unitFaction: 0,
              terrain: "plain",
              x: 7,
              unit: "none",
              y: 7,
              unitOrientation: "right"
            }, {
              terrainVariant: 0,
              building: "dropzone",
              terrain: "plain",
              x: 7,
              unit: "none",
              y: 8,
              buildingFaction: "neutral",
              buildingVariant: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 7,
              unit: "none",
              y: 9
            }
          ], [
            {
              building: "none",
              terrain: "none",
              x: 8,
              unit: "none",
              y: 0
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 8,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "shallowWater",
              x: 8,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "dessert",
              x: 8,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 8,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "plain",
              x: 8,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "dropzone",
              terrain: "plain",
              x: 8,
              unit: "none",
              y: 6,
              buildingFaction: 2,
              buildingVariant: 2
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "plain",
              x: 8,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 8,
              unit: "none",
              y: 8
            }, {
              terrainVariant: 1,
              building: "none",
              terrain: "mountain",
              x: 8,
              unit: "none",
              y: 9
            }
          ], [
            {
              building: "none",
              terrain: "none",
              x: 9,
              unit: "none",
              y: 0
            }, {
              building: "none",
              terrain: "none",
              x: 9,
              unit: "none",
              y: 1
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 9,
              unit: "none",
              y: 2
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "shallowWater",
              x: 9,
              unit: "none",
              y: 3
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "shallowWater",
              x: 9,
              unit: "none",
              y: 4
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 9,
              unit: "none",
              y: 5
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "deepWater",
              x: 9,
              unit: "none",
              y: 6
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 9,
              unit: "none",
              y: 7
            }, {
              terrainVariant: 0,
              building: "none",
              terrain: "mountain",
              x: 9,
              unit: "none",
              y: 8
            }, {
              building: "none",
              terrain: "none",
              x: 9,
              unit: "none",
              y: 9
            }
          ]
        ]
      })
    ]
  ])